DROP TABLE IF EXISTS pets CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS animals CASCADE;

CREATE TABLE owners (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(30) NOT NULL,
  city VARCHAR(30) NOT NULL
);

CREATE TABLE animals (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE pets (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(32) NOT NULL,
  color VARCHAR(32) NOT NULL,
  size VARCHAR(32) NOT NULL,
  owner_id INTEGER REFERENCES owners(id) ON DELETE CASCADE,
  animal_id INTEGER REFERENCES animals(id) ON DELETE CASCADE
);